const RouteName = {
    SPLASH_SCREEN: "SplashScreen",
    GET_STARTED_SCREEN: "GetstartedSliderscreen",
    LOGIN_AND_REGISTRATION: "LoginandRegistrationScreen",
    WELCOME_SUMANYA: "WelcomeSumnya",
    LOCATION_HOME_OFFICE_SCREEN: "LocationHomeOfficeScreen",
    CONFORMLOCATION_SET: "ConformLocation",
    HOME_SCREEN: "Homescreen",
    POPULAR_SCREEN: "PopularScreen",
    HOSPITAL_MEDICINE_SCREEN: "HospitalsSMedicinecreen",
    PRODUCT_LIST_ITEM: "ProductItemList",
    PRODUCT_DETAILS_SCREEN: "ProductDetailesScreen",
    CART_TAB: "Product",
    PRODUCT_TAB: "Product",
    Favorite_TAB: "Favorite",
    CHECK_OUT: "CheckOutScreen",
    PROFILE_TAB: "Profile",
    Vet_PROFILE_TAB: "VetProfile",
    HOME_TAB: "Home",
    DRAWER_HELP_SCREEN: "HelpScreen",
    PAYMENTSCREEN: "PaymentScreen",
    SETTTING_SCREEN: "SettingsScreen",
    ALL_BOOK_MARK_SCREEN: "AllBookMarkScreen",
    NOTIFICATION_SCREEN: "DrawerNavigationNotification",
    YOUR_ORDER_SCREEN: "My Orders",
    OTP_VERIFY_SCREEN: "OtpVeryfyScreen",
    ORDER_TAB_SCREEN: "AddOrderitemScreen",
    CREDIT_CARD_SCREEN_SET: "CreditCardScreen",
    PAYMENT_SUCCESSFULLY: "PaytmSuccessFully",
    RATING_SCREEN_SET: "RatingScreen",
    EDIT_LOCATION_SCREEN: "EditLocationScreen",
    EDIT_PROFILE_SCREEN: "EditProfileScreen",
    FORGET_PASSWORD_SCREEN: "ForgotPassword",
    CATEGORY_TAB: "Category",
    FAQ_SCREEN: "FAQScreen",
    VIDEO_TAB: "Video",
    PAYMENT_HISTORY: "PaymentHistoryScreen", 
    PRODUCT_CATEGORY: "ProductCategory",
    VIDEO_PLAY_SCREEN: "VideoPlay",
    CART_SCREEN: "Cart",
    CHAT_WITH_DOCTOR_SCREEN: "ChatScreen",
    DOCTOR_CONSULTANT_SCREEN: "ChatDoctorScreen"
}
export default RouteName;