export {default as AllBookMarkStyle} from './AllBookMarkStyle';
// export {default as ChatScreenStyle} from './ChatScreenStyle';
export {default as FastFoodeStyle} from './FastFoodeStyle';
export {default as HelpScreenStyle} from './HelpScreenStyle';
export {default as Hospitalmediction} from './FriesRiceListingStyle';
export {default as NotificationStyle} from './NotificationStyle';
export {default as PaymentStyle} from './ManjePaymentStyle';
export {default as PopularCuisinesStyle} from './PopularCuisinesStyle';
export {default as ProductDetailes} from './SelectItemStyle_15';
export {default as ProductitemList} from './FriesRiceDrtailesScreen_14_Style';
export {default as SettingStyle} from './SettingscreenStyle';
export {default as Addorderitemset} from './TrackOrderScreen';
export {default as YourOrderScreenStyle} from './YourOrderScreenStyle';
export {default as PaymentHistoryStyle} from './PaymentHistoryStyle';
